### ISSUE TITLE
Secret mount requested twice by Interlink

### ISSUE THREAD

**Issue by ttedeschi** [interlink-hq/interLink#117]
When submitting a pod with a secret mount, I see that the secret is listed twice in the request by InterLink. To reproduce:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: OnFailure
  containers:
  - image: docker://busybox:latest
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
    - name: foo2
      mountPath: "/etc/foo2"
      readOnly: true
    command:
      - sleep
      - "100"
    imagePullPolicy: Always
    name: busyecho1
    resources:
      requests:
        #memory: "3000"
        cpu: "1"
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    type: virtual-kubelet
    kubernetes.io/hostname: test-vk
  tolerations:
  - key: virtual-node.interlink/no-schedule
    operator: Exists
  volumes:
  - name: foo
    configMap:
      name: my-configmap
  - name: foo2
    secret:
      secretName: mysecret
```

```
$ kubectl describe secret
Name:         mysecret
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
username:  9 bytes
password:  9 bytes
```

This leads to:
```json
[{"pod":{"metadata":{"name":"test-pod","namespace":"default","uid":"0a02fc8d-60ec-4aca-b9c5-3623205511a2","resourceVersion":"4306802","creationTimestamp":"2023-11-16T11:53:27Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Pod\",\"metadata\":{\"annotations\":{},\"name\":\"test-pod\",\"namespace\":\"default\"},\"spec\":{\"containers\":[{\"command\":[\"sleep\",\"100\"],\"image\":\"docker://busybox:latest\",\"imagePullPolicy\":\"Always\",\"name\":\"busyecho1\",\"resources\":{\"requests\":{\"cpu\":\"1\"}},\"volumeMounts\":[{\"mountPath\":\"/etc/foo\",\"name\":\"foo\",\"readOnly\":true},{\"mountPath\":\"/etc/foo2\",\"name\":\"foo2\",\"readOnly\":true}]}],\"dnsPolicy\":\"ClusterFirst\",\"nodeSelector\":{\"beta.kubernetes.io/os\":\"linux\",\"kubernetes.io/hostname\":\"test-vk\",\"kubernetes.io/role\":\"agent\",\"type\":\"virtual-kubelet\"},\"restartPolicy\":\"OnFailure\",\"tolerations\":[{\"key\":\"virtual-node.interlink/no-schedule\",\"operator\":\"Exists\"}],\"volumes\":[{\"configMap\":{\"name\":\"my-configmap\"},\"name\":\"foo\"},{\"name\":\"foo2\",\"secret\":{\"secretName\":\"mysecret\"}}]}}\n"},"managedFields":[{"manager":"kubectl-client-side-apply","operation":"Update","apiVersion":"v1","time":"2023-11-16T11:53:27Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"busyecho1\"}":{".":{},"f:command":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:resources":{".":{},"f:requests":{".":{},"f:cpu":{}}},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{},"f:volumeMounts":{".":{},"k:{\"mountPath\":\"/etc/foo\"}":{".":{},"f:mountPath":{},"f:name":{},"f:readOnly":{}},"k:{\"mountPath\":\"/etc/foo2\"}":{".":{},"f:mountPath":{},"f:name":{},"f:readOnly":{}}}}},"f:dnsPolicy":{},"f:enableServiceLinks":{},"f:nodeSelector":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{},"f:tolerations":{},"f:volumes":{".":{},"k:{\"name\":\"foo\"}":{".":{},"f:configMap":{".":{},"f:defaultMode":{},"f:name":{}},"f:name":{}},"k:{\"name\":\"foo2\"}":{".":{},"f:name":{},"f:secret":{".":{},"f:defaultMode":{},"f:secretName":{}}}}}}}]},"spec":{"volumes":[{"name":"foo","configMap":{"name":"my-configmap","defaultMode":420}},{"name":"foo2","secret":{"secretName":"mysecret","defaultMode":420}},{"name":"kube-api-access-5xtnz","projected":{"sources":[{"serviceAccountToken":{"expirationSeconds":3607,"path":"token"}},{"configMap":{"name":"kube-root-ca.crt","items":[{"key":"ca.crt","path":"ca.crt"}]}},{"downwardAPI":{"items":[{"path":"namespace","fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}]}}],"defaultMode":420}}],"containers":[{"name":"busyecho1","image":"docker://busybox:latest","command":["sleep","100"],"resources":{"requests":{"cpu":"1"}},"volumeMounts":[{"name":"foo","readOnly":true,"mountPath":"/etc/foo"},{"name":"foo2","readOnly":true,"mountPath":"/etc/foo2"},{"name":"kube-api-access-5xtnz","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"OnFailure","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","nodeSelector":{"beta.kubernetes.io/os":"linux","kubernetes.io/hostname":"test-vk","kubernetes.io/role":"agent","type":"virtual-kubelet"},"serviceAccountName":"default","serviceAccount":"default","nodeName":"test-vk","securityContext":{},"schedulerName":"default-scheduler","tolerations":[{"key":"virtual-node.interlink/no-schedule","operator":"Exists"},{"key":"node.kubernetes.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"node.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}],"priority":0,"enableServiceLinks":true,"preemptionPolicy":"PreemptLowerPriority"},"status":{"phase":"Pending","conditions":[{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2023-11-16T11:53:27Z"}],"qosClass":"Burstable"}},"container":[{"name":"busyecho1","configMaps":[{"metadata":{"name":"my-configmap","namespace":"default","uid":"aee9a1dd-08eb-44e7-871e-a9462e3f6bb5","resourceVersion":"861393","creationTimestamp":"2023-08-11T08:39:17Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"data\":{\"key1\":\"value1\",\"key2\":\"value2\",\"key3\":\"value3\"},\"kind\":\"ConfigMap\",\"metadata\":{\"annotations\":{},\"name\":\"my-configmap\",\"namespace\":\"default\"}}\n"},"managedFields":[{"manager":"kubectl-client-side-apply","operation":"Update","apiVersion":"v1","time":"2023-08-11T08:39:17Z","fieldsType":"FieldsV1","fieldsV1":{"f:data":{".":{},"f:key1":{},"f:key2":{},"f:key3":{}},"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}}}}]},"data":{"key1":"value1","key2":"value2","key3":"value3"}}],"secrets":[{"metadata":{"name":"mysecret","namespace":"default","uid":"8eabe384-8076-4ce3-9386-ce2dd7d0fa62","resourceVersion":"861396","creationTimestamp":"2023-08-11T08:39:22Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"data\":{\"password\":\"cGFzc3dvcmQx\",\"username\":\"dXNlcm5hbWUx\"},\"kind\":\"Secret\",\"metadata\":{\"annotations\":{},\"name\":\"mysecret\",\"namespace\":\"default\"},\"type\":\"Opaque\"}\n"},"managedFields":[{"manager":"kubectl-client-side-apply","operation":"Update","apiVersion":"v1","time":"2023-08-11T08:39:22Z","fieldsType":"FieldsV1","fieldsV1":{"f:data":{".":{},"f:password":{},"f:username":{}},"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:type":{}}}]},"data":{"password":"...","username":"..."},"type":"Opaque"},{"metadata":{"name":"mysecret","namespace":"default","uid":"8eabe384-8076-4ce3-9386-ce2dd7d0fa62","resourceVersion":"861396","creationTimestamp":"2023-08-11T08:39:22Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"data\":{\"password\":\"cGFzc3dvcmQx\",\"username\":\"dXNlcm5hbWUx\"},\"kind\":\"Secret\",\"metadata\":{\"annotations\":{},\"name\":\"mysecret\",\"namespace\":\"default\"},\"type\":\"Opaque\"}\n"},"managedFields":[{"manager":"kubectl-client-side-apply","operation":"Update","apiVersion":"v1","time":"2023-08-11T08:39:22Z","fieldsType":"FieldsV1","fieldsV1":{"f:data":{".":{},"f:password":{},"f:username":{}},"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:type":{}}}]},"data":{"password":"...","username":"..."},"type":"Opaque"}],"emptyDirs":null}]}]
```
Where the mysecret entry is repeated (username and password are omitted)
