### ISSUE TITLE
Init containers are not propagated to the sidecar

### ISSUE THREAD

**Issue by Bianco95** [interlink-hq/interLink#220]
# Init containers configMaps, secrets and emptyDirs are not propagated to the sidecar

When a POD has one or more init containers and those init containers have configMaps, secrets or emptyDirs in theirs specs as well as regular containers, the latter are not propagated towards the sidecar.
In fact, by debugging the object that is sent to the sidecar, the latter contains an array of objects with a key called "container" (also this is not correct, the key should be called "containers") with the following content:

```
"container": [
            {
                "name": null,
                "configMaps": null,
                "secrets": null,
                "emptyDirs": null
            }
        ]
```
The "container" array does not includes the eventually init containers but it should include them.
An example of POD is the following one:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: {{ podName }}
  namespace: {{ namespace }}

spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: {{ nodename }}

  initContainers:
    - name: init-container-example
      imagePullPolicy: Always
      image: bitnami/git
      command: 
        - git
        - clone
        - https://github.com/interTwin-eu/interLink
        - /interlink

      volumeMounts:
        - name: interlink-repo
          mountPath: /interlink
      
  containers:
    - name: regular-container
      imagePullPolicy: Always
      image: busybox:latest
      command: ["ls", "/interlink/"]
      volumeMounts:
        - name: interlink-repo
          mountPath: /interlink

  volumes:
    - name: interlink-repo
      emptyDir:
        sizeLimit: 500Mi
    
    
  dnsPolicy: ClusterFirst

  tolerations: [{"effect": "NoSchedule", "key": "virtual-node.interlink/no-schedule", "operator": "Exists"}]

```
