### ISSUE TITLE
Web Proxy support

### ISSUE THREAD

**Issue by antoinetran** [interlink-hq/interLink#256]
# Short Description of the issue

In a closed network environment, with internet access only though a authenticated web proxy, the interlink deployment fails.

## Environment

- Operating System: Redhat 8
- Other related components versions: interlink 0.3.0

## Logs, stacktrace, or other symptoms

```shell
kubectl -n interlink logs my-vk-node-5dfb4b48cc-btdb7
Defaulted container "inttw-vk" out of: inttw-vk, refresh-token
time="2024-07-11T09:53:42Z" level=info msg="Loading Virtual Kubelet config from /etc/interlink/InterLinkConfig.yaml"
time="2024-07-11T09:53:42Z" level=info msg="Trying InCluster configuration"
time="2024-07-11T09:53:42Z" level=info msg="Loading Virtual Kubelet config from /etc/interlink/InterLinkConfig.yaml"
time="2024-07-11T09:53:42Z" level=info msg=nodeLoop
time="2024-07-11T09:53:42Z" level=fatal msg="open /opt/interlink/token: no such file or directory"
```

No token because no internet.

# Summary of proposed changes

Add in ~/.interlink.yaml, a config like this:
```
proxy:
  user:
  password
  https_proxy
  http_proxy
  no_proxy
```

**Comment by antoinetran** [comment]
Workaround:
I confirm that adding these env variables to `~/.interlink/interlink.yaml` fixed the issue:
```
        - name: TOKEN_PATH
          value: /opt/interlink/token
        - name: HTTPS_PROXY
          value: http://user:password@proxy:port
        - name: HTTP_PROXY
          value: http://user:password@proxy:port
        command:
        - python3
        - /opt/refresh.py
```
