### ISSUE TITLE
docs/bug: setting Gi suffix as given in docs causes installation to fail down the line

### ISSUE THREAD

**Issue by waveywaves** [interlink-hq/interLink#316]
# Short Description of the issue

Setting the `node_limits.memory` as given in the docs [here](https://intertwin-eu.github.io/interLink/docs/guides/deploy-interlink#configuring-your-virtual-kubelet-setup-remote-host) 

```
interlink_ip: 192.168.1.127
interlink_port: 30443
interlink_version: 0.2.1-patch2
kubelet_node_name: my-civo-node
kubernetes_namespace: interlink
node_limits:
    cpu: "10"
    memory: 256Gi
    pods: "10"
...
```
and then generating a values.yaml by running `./interlink-install`. (generates the values file below)
```
virtualNode:
  CPUs: 10
  MemGiB: 256Gi
  Pods: 10
  HTTPProxies:
    HTTP: null
    HTTPs: null
```
and then running the helm command
```
helm --debug upgrade --install --create-namespace -n interlink multipass-docker oci://ghcr.io/intertwin-eu/interlink-helm-chart/interlink  --values values.yaml
```
causes failure in deployment with the below logs

```
k logs -f deployment/multipass-docker-node    
                                                                                                          ─╯
Defaulted container "vk" out of: vk, refresh-token
time="2024-10-29T10:26:01Z" level=info msg="Loading Virtual Kubelet config from /etc/interlink/InterLinkConfig.yaml"
panic: invalid memory value 256GiGi

goroutine 1 [running]:
main.main()
        /app/cmd/virtual-kubelet/main.go:119 +0x1e98
```

This is either a bug or a error in docs. This can be resolved with a change in the docs.
## Environment

- Operating System: Ubuntu
- Other related components versions: 0.3.1-patch

## Steps to reproduce

-- given above

# Summary of proposed changes

update docs and `interlink-install --init` command which generates the `.interlink.yaml` file
