### ISSUE TITLE
Enable defining additional custom taints and labels to virtual nodes from interlink config

### ISSUE THREAD

**Issue by landerlini** [interlink-hq/interLink#341]
While it is possible to add additional taints to virtual nodes with the command line tool,
```bash
kubectl taint node <the node> someTaint=someValue:NoSchedule
```
it would be helpful to introduce some automation-friendly way of defining labels and taints for the virtual nodes.

I propose to add the `node-label` and `node-taint` fields in the `interlink.conf` file, that is already part of the IaaC repositories.
To avoid diverging with notations while preserving synthesis, consider copying from [RKE2 configuration](https://docs.rke2.io/install/configuration#configuration-file):
```yaml
node-label:
  - other=what
  - foo=three
node-taint:
  - charlie=delta:NoSchedule
```

**Comment by Bianco95** [comment]
Thank you for opening this issue! The configuration file used to set up various parameters for the VK is the **InterLinkConfig.yaml** file. Below is an example structure for this file:
```
VKTokenFile: "$HOME/interLink/token"
InterlinkURL: "http://XXX.XXX.XXX.XXX"
CommandPrefix: ""
ExportPodData: true
ServiceAccount: "interlink"
Namespace: "vk"
VerboseLogging: true
ErrorsOnlyLogging: false
CPU: 100
Memory: 128Gi
Pod: 100
```
To enhance functionality by including node taints and labels, the idea is to set these information in this configuration file. Here's an example of the proposed structure:
```
NodeLabels:
    - "virtual-kubelet=interlink"
    - "cool-node=true"
NodeTaints:
    - Key: "accelerator"
      Value: "A100"
      Effect: "NoSchedule"
```
Additionally, we will update the Helm chart to support passing this information during the VK installation. Below is an example snippet of the updated Helm configuration:
```
virtualNode:
  image: ghcr.io/intertwin-eu/interlink/virtual-kubelet-inttw:0.3.6
  CPUs: 8
  MemGiB: 49
  Pods: 100
  NvidiaGPU: 1
  AMDGPU: 0
  IntelGPU: 0
  NodeLabels:
    - "virtual-kubelet=interlink"
    - "cool-node=true"
  NodeTaints:
    - Key: "accelerator"
      Value: "A100"
      Effect: "NoSchedule"
 ```

**Comment by dciangot** [comment]
Matter of readability and consistency. All the gpus entry should go nested into a unique gpus key. Also,  I think gpu field should be let free to include any strimg in case the model of the gpu is needed.

Also let's use a yaml friendly naming. It's a long time mistake we did some time ago, but let's use non-golang naming for the yaml files. I'm ok with camel case, but I'd like to remove the capital initial letter (that crearly comes from go)

**Comment by dciangot** [comment]
Also image it ends in being out scope, since al the rest is about k8s node definition, while the image is about vk

**Comment by Bianco95** [comment]
yes, gpus but also CPUs, MemGiB, Pods (whose names will have to be changed by removing the initial camelcase) can be organized better, for example a "resources" field can be used to put those information under it. A new branch *341-enable-defining-additional-custom-taints-and-labels-to-virtual-nodes-from-interlink-config* has been created to fix these aspects that I am currently working on.

**Comment by Bianco95** [comment]
Regarding accelerator resources such as GPUs or FPGAs, a solution can be to define these properties under the *accelerators* key as follows:

```
accelerators:
  - resource_type: nvidia.com/gpu
    model: a100
    available: 1
  - resource_type: xilinx.com/fpga
    model: U55C
    available: 1
```

The *model* of the resource will be used to automatically add a label to the virtual node. For example, the following label would be applied for the NVIDIA GPU:

```
nvidia-gpu-type=a100
```

This approach allows users to target specific virtual nodes with particular resources by using the *nodeSelector* property in their pod specification. For example, a pod could specify:

```
nodeSelector:
  nvidia-gpu-type: a100
```

This ensures that the pod will be scheduled only to virtual nodes equipped with the specified GPU or FPGA model.
