### ISSUE TITLE
Running pod displayed as `Waiting for init containers` by `kubectl`.

### ISSUE THREAD

**Issue by landerlini** [interlink-hq/interLink#366]
Hello. 
I am updating my plugin to 0.3.7 and I am trying to cope with the new status system (which I like a lot more than the previous one, thanks).

Unfortunately, I cannot have my running pods displayed as `Running`. 

As you know, the plugin sets the containerStatuses and then interlink builds up the summary defining pod `phase` and `reason`.

Can you have a look to the `containerStatuses` below and let me know if there is a legitimate reason for setting `reason` to `Waiting for init containers` and I should set the statuses of containers differently or if it is a bug on your side?

Note that the `phase` field is set correctly to `Running` so `kueue` interpret properly the status of the pod and propagates it correctly to the application level. It's just a matter of what kubectl displays.

```yaml
  containerStatuses:
  - image: ""
    imageID: ""
    lastState: {}
    name: notebook
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: null
  hostIP: 10.42.6.18
  initContainerStatuses:
  - image: ""
    imageID: ""
    lastState: {}
    name: init-sandbox
    ready: false
    restartCount: 0
    state:
      terminated:
        exitCode: 0
        finishedAt: null
        reason: Completed
        startedAt: null
  phase: Running
  podIP: 10.42.6.18
  podIPs:
  - ip: 10.42.6.18
  reason: Waiting for init containers
  startTime: "2025-01-26T10:52:35Z"
```
