### ISSUE TITLE
Pod with ProjectedVolumes fails if VK kubernetes API endpoints are not configured

### ISSUE THREAD

**Issue by dciangot** [interlink-hq/interLink#372]
As per subject, we seem to have a small break in compatibility with ProjectedVolume support. 

The following pod will create automatically a service account token (not really crucial for the pod functionality):

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: vol-config-0621f662-4c29-4672-b360-d40bfb1a7191
  namespace: interlink
data:
  config-map-script.py: |
    print ("hello configurable world")

    with open("/shared-vol1/config", "w") as f:
      print ("hello configurable world", file=f)

    with open("/shared-vol2/config", "w") as f:
      print ("hello configurable world", file=f)

---

apiVersion: v1
kind: Secret
metadata:
  name: secret-0621f662-4c29-4672-b360-d40bfb1a7191
  namespace: interlink
type: Opaque
stringData:
  secret-script.py: |
    print ("hello secret world")

    with open("/shared-vol1/secret", "w") as f:
      print ("hello configurable world", file=f)

    with open("/shared-vol2/secret", "w") as f:
      print ("hello configurable world", file=f)

---

apiVersion: v1
kind: Pod
metadata:
  name: python-vol-0621f662-4c29-4672-b360-d40bfb1a7191
  namespace: interlink
  annotations: {"slurm-job.vk.io/flags": "--job-name=test-pod-cfg -t 2800", "slurm-job.vk.io/image-root": "docker://"}

spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: virtual-kubelet

  containers:
    - name: config
      imagePullPolicy: Always
      image: python:alpine
      command: ["python", "/config-map/config-map-script.py"]
      volumeMounts:
        - name: shared-vol1
          mountPath: /shared-vol1
        - name: config-map
          mountPath: /config-map
        - name: shared-vol2
          mountPath: /shared-vol2

    - name: secret
      imagePullPolicy: Always
      image: python:alpine
      command: ["python", "/secrets/secret-script.py"]
      volumeMounts:
        - name: shared-vol1
          mountPath: /shared-vol1
        - name: secret
          mountPath: /secrets
        - name: shared-vol2
          mountPath: /shared-vol2


  volumes:
    - name: config-map
      configMap:
        name: vol-config-0621f662-4c29-4672-b360-d40bfb1a7191
        items:
          - key: config-map-script.py
            path: config-map-script.py
    - name: secret
      secret:
        secretName: secret-0621f662-4c29-4672-b360-d40bfb1a7191
        items:
          - key: secret-script.py
            path: secret-script.py
    - name: shared-vol1
      emptyDir:
        sizeLimit: 50Mi
    - name: shared-vol2
      emptyDir:
        sizeLimit: 50Mi


  dnsPolicy: ClusterFirst

  tolerations: [{"effect": "NoSchedule", "key": "virtual-node.interlink/no-schedule", "operator": "Exists"}]
```

Two issues to be adressed:
1. allow from configuration to explicitly IGNORE the projected volumes
2. the pod above (if the image is already cached) might start before the config map has been registered by kubernetes. Causing a failure of the pod preparation. This was seen before and looks like a regression.
