### ISSUE TITLE
Invalid client credentials error when installing InterLink with EGI OIDC integration (Demo environment)

### ISSUE THREAD

**Issue by Bianco95** [interlink-hq/interLink#413]
The issue arises during the initial installation phase of InterLink using the *interlink-remote.sh* installation script. 
I configured a client on EGI (https://aai.egi.eu/federation/egi/home) and requested the following grant types:

- authorization code
- token-exchange
- device code 
 
and the following scopes:

- openid 
- voperson_id 
- email
- profile
- voperson_external_affiliation
- entitlements
- offline_access

The client is set to use the **DEMO integration environment**. 
I created the *installer.yaml* configuration file as follows:

```
interlink_ip: <ip-address>
interlink_port: <port-number>
interlink_version: 0.4.0
kubelet_node_name: my-vk-node
kubernetes_namespace: interlink
node_limits:
    cpu: "10"
    memory: "256"
    pods: "10"
oauth:
  provider: oidc
  issuer: https://aai.egi.eu/auth/realms/egi
  scopes:
    - "openid"
    - "email"
    - "profile"
    - "offline_access"
  grant_type: authorization_code
  group_claim: "email"
  group: "giulio.bianchini@pg.infn.it"
  token_url: "https://aai.egi.eu/auth/realms/egi/protocol/openid-connect/token"
  device_code_url: "https://aai.egi.eu/auth/realms/egi/protocol/openid-connect/auth/device"
  client_id: "client-id"
  client_secret: "client-secret"
insecure_http: true
```
Then, when running:

```
./interlink-remote.sh install
```

This error is returned:

```
Response: {"error":"invalid_client","error_description":"Invalid client or Invalid client credentials"}
```

This error still occurs even when using the aai-demo endpoint in the installer configuration. 
The issue can be reproduced by creating an executable from the following Go code snippet:

```
import (
	"context"
	"golang.org/x/oauth2"
)

func requestToken() (*oauth2.Token, error) {

	ctx := context.Background()

	cfg := oauth2.Config{
		ClientID:     "client-id",
		ClientSecret: "client-secret",
		Endpoint: oauth2.Endpoint{
			TokenURL:      "https://aai.egi.eu/auth/realms/egi/protocol/openid-connect/token",
			DeviceAuthURL: "https://aai.egi.eu/auth/realms/egi/protocol/openid-connect/auth/device",
		},
	}

	deviceAuthResponse, err := cfg.DeviceAuth(ctx, oauth2.AccessTypeOffline) // -> this call raise the error
	if deviceAuthResponse == nil {
		fmt.Println("Error obtaining device authorization: ", err)
		return nil, fmt.Errorf("error obtaining device authorization: %v", err)
	}

	token, err := cfg.DeviceAccessToken(ctx, deviceAuthResponse)
	if err != nil {
		fmt.Println("Error requesting token: ", err)
		return nil, fmt.Errorf("error obtaining token: %v", err)
	}

	return token, nil
}
```

**Comment by dciangot** [comment]
Which is the action item on interLink side here @Bianco95 ?

**Comment by Bianco95** [comment]
Just update the documentation to specify to use the EGI's public client

```
oauth:
  provider: oidc
  issuer: https://aai.egi.eu/auth/realms/egi
  scopes:
    - "openid"
    - "email"
    - "offline_access"
    - "profile"
  audience: oidc-agent
  grant_type: authorization_code
  group_claim: email
  group: "YOUR EMAIL HERE"
  token_url: "https://aai.egi.eu/auth/realms/egi/protocol/openid-connect/token"
  device_code_url: "https://aai.egi.eu/auth/realms/egi/protocol/openid-connect/auth/device"
  client_id: "oidc-agent"
  client_secret: ""
```
And collaborate with EGI teams to identify the cause of the error.
