### ISSUE TITLE
interlink-installer always asks for oauth settings

### ISSUE THREAD

**Issue by vtj-mizuno** [interlink-hq/interLink#415]
If only ssh-tunnel is used for the connection between Virtual Kubelet and InterLink, I think oauth configuration is not necessary.
However, if I remove the oauth configuration from the .interlink.yaml, the interlink-installer fails.

### How to reproduce

1. run interlink-installer --init

2. edit .interlink.yaml 

```
interlink_ip: 172.16.xxx.xxx
interlink_port: 30443
interlink_version: 0.4.0
kubelet_node_name: vk-node
kubernetes_namespace: interlink
node_limits:
    cpu: "10"
    memory: "256"
    pods: "10"
insecure_http: true
```

3. run interlink-installer

```
$ ./interlink-installer
panic: wrong grant type specified in the configuration. Only client_credentials and authorization_code are supported
```

In environments that do not require oauth, we believe an option to skip the oauth setting is necessary.
